### ISSUE TITLE
1.2.2 Use Case Diagram

### ISSUE THREAD

**Issue by SaltedEggYok** [SaltedEggYok/INF2001_P6-7#11]
Description of task: This task involves the correct distinguishing of use cases from the functional requirements to create an accurate use case diagram, which describes the high-level functionality and scope of the system without showcasing process flow.

Goal of task: The task aims to provide an overview of the functionality of the system by using the use case diagram to showcase any actions an actors is able to perform within the system.

Success of the task is dependent on the correct generation of the use case diagram from the functional requirements.

Allocated time: 2 Hours

Start Date:  19/9/2023
End Date:  21/9/2023

Owner: Thaddeus Kwok
Status: Completed

Priority: High

**Comment by davidlane23** [comment]
**Describe the work done in detail:**

In this task, the actors, and relevant use cases were accurately identified from the functional requirements in order to create the use case diagram. Each use case was labelled with a unique identifier and the diagram was mapped out, ensuring that there was no indication of flow.

The task was successful as diagram contained all use cases that had successfully described the high level functionalities of the system and also illustrated the relationships between the actors and the use cases.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule and does not need to be committed to the repository.

Start Date : 16/9/2023
End Date: 16/9/2023
