### ISSUE TITLE
2.1.1 Noun Extraction

### ISSUE THREAD

**Issue by davinlim23** [SaltedEggYok/INF2001_P6-7#50]
Description of task: The task entails the extracting of nouns by developing a concise solution description. 

Goal of task: The objective of this task is to correctly extract the nouns in order for future identification of candidate classes. 

Success of the task is dependent on the correct extraction of all nouns from the concise solution description

Allocated time: 1 day

Start Date: 25/9/23
End Date: 26/9/23

Owner: Thaddeus Kwok
Status: To Do

Priority: High

**Comment by Thaddaeus-K** [comment]
Description of work done:
A concise description of the solution was done so that noun extraction could be performed to identify candidate classes that needs remembrance or services/ operations and has multiple attributes. This work is part of the work to model the domain which will help in the drawing of the class diagram.

The completion deadline for the project remains unchanged. This phase of work was planned and executed within the allocated time frame which aligns with the overall project schedule.

Start Date: 25/9/23
End Date: 26/9/23
